### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by juev** [rumyantseva/hello-mongodb#1]
Hello! :)

And merry christmas!

I have a few silly questions, if you'll excuse me.

1. As I can see you use the same variable for error:
  ```golang
  // Load the root CA certificate
  rootCA, err := os.ReadFile("./certs/rootCA.pem")
  if err != nil {
    log.Fatal(err)
  }
  ...
  // Load the client certificate and key
  cert, err := tls.LoadX509KeyPair("./certs/client.crt", "./certs/client.key")
  if err != nil {
    log.Fatal(err)
  }
  ```

  One variable err for errors. Its mean we will shadow this variable, is not? Its not critical?

2. Why don't you use scopes for variables? For examples:
  ```golang
  if ok := roots.AppendCertsFromPEM(rootCA); !ok {
    log.Fatal("failed to parse root certificate")
  }
  ```

  in this example ok variable exist only on this scope. The same technique can be used for the variable err.

**Comment by rumyantseva** [comment]
@juev hohoho, merry Christmas, Denis! 🎄 Thank you for sending this issue! 

1. Yes, you are 100% right about shadowing. In real-life apps, I prefer to avoid shadowing. I expect the `go-vet` linter to complain about some lines in this repo, and I'd fix them in a real-life app.  As this is just for testing purposes, it's ok'ish to ignore shadowing here. Anyway, any error is a fatal error here, so in this particular code, there is no chance to mix up errors. 

2. Again, for the same reason - I didn't really pay attention. In real-life code, I expect reviewers to complain if such code is present. And I like your approach to noticing such things! 👍 

Overall, my goal with this repo was to try various (correct and wrong) TLS certificates when connecting to MongoDB to see how MongoDB would behave and what client properties can change this behavior.

**Comment by juev** [comment]
Thank you!
